In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("../dataset/claim_data.csv")

df.head()

,Claim ID,Provider ID,Patient ID,Date of Service,Billed Amount,Procedure Code,Diagnosis Code,Allowed Amount,Paid Amount,Insurance Type,Claim Status,Reason Code,Follow-up Required,AR Status,Outcome
0,0HO1FSN4AP,126528997,7936697103,08/07/2024,304,99231,A02.1,218,203,Self-Pay,Paid,Incorrect billing information,Yes,Pending,Partially Paid
1,9U86CI2P5A,6986719948,1547160031,06/21/2024,348,99213,A16.5,216,206,Medicare,Paid,Pre-existing condition,Yes,Open,Denied
2,1QEU1AIDAU,1355108115,2611585318,07/04/2024,235,99213,A00.1,148,119,Commercial,Under Review,Duplicate claim,No,Denied,Denied
3,WH7XDS8CEO,9991055906,7167948632,05/26/2024,112,99215,A18.6,79,69,Medicare,Denied,Authorization not obtained,No,Partially Paid,Denied
4,M6OJEZ8KGI,7382167012,2140226267,07/16/2024,406,99238,A17.9,320,259,Medicare,Denied,Authorization not obtained,No,On Hold,Denied

In [4]:
df.shape

(1000, 15)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Claim ID            1000 non-null   object
 1   Provider ID         1000 non-null   int64
 2   Patient ID          1000 non-null   int64
 3   Date of Service     1000 non-null   object
 4   Billed Amount       1000 non-null   int64
 5   Procedure Code      1000 non-null   int64
 6   Diagnosis Code      1000 non-null   object
 7   Allowed Amount      1000 non-null   int64
 8   Paid Amount         1000 non-null   int64
 9   Insurance Type      1000 non-null   object
 10  Claim Status        1000 non-null   object
 11  Reason Code         1000 non-null   object
 12  Follow-up Required  1000 non-null   object
 13  AR Status           1000 non-null   object
 14  Outcome             1000 non-null   object
dtypes: int64(6), object(9)
memory usage: 117.3+ KB

In [6]:
df.describe(include='all')

,Claim ID,Provider ID,Patient ID,Date of Service,Billed Amount,Procedure Code,Diagnosis Code,Allowed Amount,Paid Amount,Insurance Type,Claim Status,Reason Code,Follow-up Required,AR Status,Outcome
count,1000,1.000000e+03,1.000000e+03,1000,1000.00000,1000.000000,1000,1000.000000,1000.000000,1000,1000,1000,1000,1000,1000
unique,1000,NaN,NaN,143,NaN,NaN,100,NaN,NaN,4,3,8,2,6,3
top,0HO1FSN4AP,NaN,NaN,07/28/2024,NaN,NaN,A05.4,NaN,NaN,Medicaid,Under Review,Authorization not obtained,Yes,Partially Paid,Paid
freq,1,NaN,NaN,16,NaN,NaN,19,NaN,NaN,259,338,154,522,184,357
mean,NaN,4.909473e+09,5.112327e+09,NaN,297.19100,99223.969000,NaN,223.112000,200.754000,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,2.866473e+09,2.919255e+09,NaN,116.36365,8.390736,NaN,90.784731,83.353688,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,5.364682e+06,9.455298e+06,NaN,100.00000,99213.000000,NaN,64.000000,53.000000,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,2.460360e+09,2.600572e+09,NaN,197.00000,99215.000000,NaN,147.750000,133.000000,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,5.002762e+09,5.216802e+09,NaN,297.00000,99222.000000,NaN,225.000000,200.000000,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,7.313899e+09,7.753702e+09,NaN,395.00000,99232.000000,NaN,289.000000,262.000000,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,9.991056e+09,9.964057e+09,NaN,500.00000,99238.000000,NaN,442.000000,423.000000,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
df.isnull().sum()

Claim ID              0
Provider ID           0
Patient ID            0
Date of Service       0
Billed Amount         0
Procedure Code        0
Diagnosis Code        0
Allowed Amount        0
Paid Amount           0
Insurance Type        0
Claim Status          0
Reason Code           0
Follow-up Required    0
AR Status             0
Outcome               0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(0)

In [12]:
df["Date of Service"] = pd.to_datetime(df["Date of Service"])

In [13]:
df["Year"] = df["Date of Service"].dt.year
df["Month"] = df["Date of Service"].dt.month
df["Quarter"] = df["Date of Service"].dt.quarter

In [15]:
df["Difference"] = df["Billed Amount"] - df["Paid Amount"]

In [16]:
df.to_csv("../dataset/health_claims_cleaned.csv",index=False)